DEVICE_PACKAGE_OVERLAYS += device/intel/cherrytrail/cht_cr_rvp/overlay

BOARD_FLASHFILES += \
        device/intel/cherrytrail/cht_cr_rvp/oemvars.txt:oemvars.txt

# Enable to use DPCM driver in audio offload HAL
MRFLD_AUDIO := true
# enable to use Audio Scalability in audio offload HAL
AUDIO_OFFLOAD_SCALABILITY := true

# ----------------- BEGIN MIX-IN DEFINITIONS -----------------
# Mix-In definitions are auto-generated by mixin-update
##############################################################
# Source: device/intel/mixins/groups/boot-arch/efi/BoardConfig.mk
##############################################################
#
# -- OTA RELATED DEFINES --
#

# tell build system where to get the recovery.fstab. Userfastboot
# uses this too.
TARGET_RECOVERY_FSTAB ?= $(TARGET_DEVICE_DIR)/fstab

# Used by ota_from_target_files to add platform-specific directives
# to the OTA updater scripts
TARGET_RELEASETOOLS_EXTENSIONS ?= device/intel/common/recovery/releasetools.py

# Adds edify commands swap_entries and copy_partition for robust
# update of the EFI system partition
TARGET_RECOVERY_UPDATER_LIBS := libupdater_esp

# Extra libraries needed to be rolled into recovery updater
# libgpt_static is needed by libupdater_esp
TARGET_RECOVERY_UPDATER_EXTRA_LIBS := libcommon_recovery libgpt_static

# By default recovery minui expects RGBA framebuffer
# also affects UI in Userfastboot
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"


#
# FILESYSTEMS
#

# NOTE: These values must be kept in sync with BOARD_GPT_INI
BOARD_SYSTEMIMAGE_PARTITION_SIZE ?= 2684354560
BOARD_BOOTLOADER_PARTITION_SIZE ?= 104857600
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE ?= 268435456
ifneq ($(BOARD_USERDATAIMAGE_PARTITION_SIZE),)
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
else
ifneq ($(CALLED_FROM_SETUP),true)
$(warning "BOARD_USERDATAIMAGE_PARTITION_SIZE not defined, please specify at the top of your device's BoardConfig.mk")
endif
endif

TARGET_USERIMAGES_USE_EXT4 := true
BOARD_FLASH_BLOCK_SIZE := 512
TARGET_USERIMAGES_SPARSE_EXT_DISABLED := false

# Partition table configuration file
BOARD_GPT_INI ?= $(TARGET_DEVICE_DIR)/gpt.ini

TARGET_BOOTLOADER_BOARD_NAME := $(TARGET_DEVICE)

#
# Trusted Factory Reset - persistent partition
#
DEVICE_PACKAGE_OVERLAYS += device/intel/common/boot/overlay
ADDITIONAL_DEFAULT_PROPERTIES += ro.frp.pst=/dev/block/by-name/android_persistent

ifeq (efi,efi)
# For fastboot-uefi we need to parse gpt.ini into
# a binary format.

#can't use := here, as PRODUCT_OUT is not defined yet
BOARD_GPT_BIN = $(PRODUCT_OUT)/gpt.bin
BOARD_FLASHFILES += $(BOARD_GPT_BIN):gpt.bin
INSTALLED_RADIOIMAGE_TARGET += $(BOARD_GPT_BIN)
else
#
# USERFASTBOOT Configuration
#
TARGET_STAGE_USERFASTBOOT := true
TARGET_USE_USERFASTBOOT := true

BOOTLOADER_ADDITIONAL_DEPS += $(PRODUCT_OUT)/fastboot.img
BOOTLOADER_ADDITIONAL_ARGS += --fastboot $(PRODUCT_OUT)/fastboot.img

BOARD_FLASHFILES += $(BOARD_GPT_INI):gpt.ini
INSTALLED_RADIOIMAGE_TARGET += $(BOARD_GPT_INI)
endif

ifneq ($(EFI_EMMC_BIN),)
BOARD_FLASHFILES += $(EFI_EMMC_BIN):emmc.bin
endif

##############################################################
# Source: device/intel/mixins/groups/config-partition/enabled/BoardConfig.mk
##############################################################
BOARD_CONFIGIMAGE_PARTITION_SIZE := 8388608
##############################################################
# Source: device/intel/mixins/groups/kernel/gmin64/BoardConfig.mk.1
##############################################################
TARGET_USES_64_BIT_BINDER := true
##############################################################
# Source: device/intel/mixins/groups/kernel/gmin64/BoardConfig.mk
##############################################################
# Specify location of board-specific kernel headers
TARGET_BOARD_KERNEL_HEADERS := device/intel/gmin-kernel/kernel-headers

KERNEL_LOGLEVEL ?= 5

BOARD_KERNEL_CMDLINE += \
        loglevel=$(KERNEL_LOGLEVEL) \
        androidboot.hardware=$(TARGET_DEVICE)\
        firmware_class.path=/system/etc/firmware \
	i915.fastboot=1

##############################################################
# Source: device/intel/mixins/groups/display-density/medium/BoardConfig.mk
##############################################################
ADDITIONAL_DEFAULT_PROPERTIES += ro.sf.lcd_density=320

##############################################################
# Source: device/intel/mixins/groups/cpu-arch/slm/BoardConfig.mk
##############################################################
TARGET_ARCH := x86
TARGET_CPU_ABI := x86
TARGET_ARCH_VARIANT := silvermont
TARGET_CPU_SMP := true

##############################################################
# Source: device/intel/mixins/groups/houdini/true/BoardConfig.mk
##############################################################
# Install Native Bridge
ifeq ($(WITH_NATIVE_BRIDGE),true)

# Enable ARM codegen for x86 with Native Bridge
BUILD_ARM_FOR_X86 := true

# Native Bridge ABI List
NB_ABI_LIST_32_BIT := armeabi-v7a armeabi
# NB_ABI_LIST_64_BIT := arm64-v8a

# Support 64 Bit Apps
ifeq ($(TARGET_SUPPORTS_64_BIT_APPS),true)
  TARGET_CPU_ABI_LIST_64_BIT ?= $(TARGET_CPU_ABI) $(TARGET_CPU_ABI2)
  ifeq ($(TARGET_SUPPORTS_32_BIT_APPS),true)
    TARGET_CPU_ABI_LIST_32_BIT ?= $(TARGET_2ND_CPU_ABI) $(TARGET_2ND_CPU_ABI2)
  endif
  ifneq ($(findstring ro.zygote=zygote32_64,$(PRODUCT_DEFAULT_PROPERTY_OVERRIDES)),)
    TARGET_CPU_ABI_LIST := \
        $(TARGET_CPU_ABI_LIST_32_BIT) \
        $(TARGET_CPU_ABI_LIST_64_BIT) \
        $(NB_ABI_LIST_32_BIT) \
        $(NB_ABI_LIST_64_BIT)
    TARGET_CPU_ABI_LIST_32_BIT += $(NB_ABI_LIST_32_BIT)
  else
    ifeq ($(TARGET_SUPPORTS_32_BIT_APPS),true)
      TARGET_CPU_ABI_LIST := \
          $(TARGET_CPU_ABI_LIST_64_BIT) \
          $(TARGET_CPU_ABI_LIST_32_BIT) \
          $(NB_ABI_LIST_32_BIT) \
          $(NB_ABI_LIST_64_BIT)
      TARGET_CPU_ABI_LIST_32_BIT += $(NB_ABI_LIST_32_BIT)
    else
      TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT) $(NB_ABI_LIST_64_BIT)
    endif
  endif
  TARGET_CPU_ABI_LIST_64_BIT += $(NB_ABI_LIST_64_BIT)

else
  TARGET_CPU_ABI_LIST_32_BIT ?= $(TARGET_CPU_ABI) $(TARGET_CPU_ABI2)
  TARGET_CPU_ABI_LIST_32_BIT += $(NB_ABI_LIST_32_BIT)
  TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_32_BIT)
endif

endif
##############################################################
# Source: device/intel/mixins/groups/graphics/ufo_gen8/BoardConfig.mk.1
##############################################################
# Select ufo gen8 libs
UFO_ENABLE_GEN := gen8

# Defines Intel library for GPU accelerated Renderscript:
OVERRIDE_RS_DRIVER := libRSDriver_intel.so

##############################################################
# Source: device/intel/mixins/groups/graphics/ufo_gen8/BoardConfig.mk
##############################################################
BOARD_KERNEL_CMDLINE += vga=current i915.modeset=1 drm.vblankoffdelay=1
USE_OPENGL_RENDERER := true
USE_INTEL_UFO_DRIVER := true
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
INTEL_VA := true
BOARD_GRAPHIC_IS_GEN := true

# System's VSYNC phase offsets in nanoseconds
VSYNC_EVENT_PHASE_OFFSET_NS := 7500000
SF_VSYNC_EVENT_PHASE_OFFSET_NS := 5000000

# Allow HWC to perform a final CSC on virtual displays
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true

ADDITIONAL_DEFAULT_PROPERTIES += \
	persist.intel.ogl.username=Developer \
	persist.intel.ogl.debug=/data/ufo.prop \
	persist.intel.ogl.dumpdebugvars=1 \
	ro.ufo.use_coreu=1

##############################################################
# Source: device/intel/mixins/groups/storage/sdcard-mmcblk1-4xUSB-sda-emulated/BoardConfig.mk
##############################################################
DEVICE_PACKAGE_OVERLAYS += device/intel/common/storage/overlay-sdcard-usb
RECOVERY_HAVE_SD_CARD := true

##############################################################
# Source: device/intel/mixins/groups/camera/isp3/BoardConfig.mk
##############################################################
# The make targets for both projects are identical
# (e.g. camera.gmin.so), so the Android.mk's wrap themselves in tests
# for these.  Set only one.  And we'll just ignore the inconsistent _.
USE_CAMERA_HAL2 := false
USE_CAMERA_HAL_3 := true

# BYT/CHT hardware generation, camera3hal builds different code for
# different ISPs
BOARD_CAMERA_IPU2_SUPPORT = true

# camera3hal won't build if this isn't true
USE_SHARED_IA_FACE = true

# Intel camera extras (HDR, face detection, panorama, red-eye detection etc.).
USE_INTEL_CAMERA_EXTRAS := true

# Selects which subdirectory to pick in libmfldadvci/ia_imaging/ia_panorama/
IA_PANORAMA_VERSION := 1.0

# No hardware JPEG encode on BYT/CHT
USE_INTEL_JPEG := false

# Must be "false" (NOT simply unset!) or else lots of camera
# depencencies will remove themselves from the build...
USE_CAMERA_STUB := false

##############################################################
# Source: device/intel/mixins/groups/bluetooth/lnp/BoardConfig.mk
##############################################################
BOARD_HAVE_BLUETOOTH := true
USE_AOSP_BLUEDROID := true
BOARD_HAVE_BLUETOOTH_RTK := true
RTK_BLUETOOTH_INTERFACE := uart
BLUETOOTH_BLUEDROID_RTK := true
BLUETOOTH_HCI_USE_RTK_H5 := true
BOARD_HAVE_BLUETOOTH_INTEL := true
BOARD_BLUETOOTH_BDROID_BUILDCFG_INCLUDE_DIR := device/intel/common/bluetooth/lnp/
DEVICE_PACKAGE_OVERLAYS += device/intel/common/bluetooth/overlay-bt-pan

##############################################################
# Source: device/intel/mixins/groups/wlan/iwlwifi/BoardConfig.mk
##############################################################
# This enables the wpa wireless driver
BOARD_HOSTAPD_DRIVER := NL80211
BOARD_WPA_SUPPLICANT_DRIVER := NL80211
WPA_SUPPLICANT_VERSION := VER_2_1_DEVEL_WCS

# Enabling iwlwifi
BOARD_USING_INTEL_IWL := true

COMBO_CHIP_VENDOR := intel
COMBO_CHIP := iwlwifi
##############################################################
# Source: device/intel/mixins/groups/widi/gen/BoardConfig.mk
##############################################################
# WIDI
INTEL_WIDI := true
INTEL_WIDI_GEN := true
##############################################################
# Source: device/intel/mixins/groups/media/ufo/BoardConfig.mk
##############################################################
# Settings for the Intel-optimized codecs and plug-ins:
USE_INTEL_MDP := true

# Settings for the Media SDK library and plug-ins:
# - USE_MEDIASDK: use Media SDK support or not
# - MFX_IPP: sets IPP library optimization to use
USE_MEDIASDK := true
MFX_IPP := p8

# Settings for ASF/AVI/MPEG4-ASP:
# - USE_INTEL_ASF_EXTRACTOR: use intel's asf_extractor lib
# - USE_SW_MPEG4: use software MPEG4 decoder including ASP support
# - USE_INTEL_IPP: use IPP acceleration in decoders
# - BOARD_USES_WRS_OMXIL_CORE: load WRS omx-il core
# - BOARD_USES_MRST_OMX: load omx-component for MPEG4-ASP
USE_INTEL_ASF_EXTRACTOR := true
USE_SW_MPEG4 := true
USE_INTEL_IPP := true
BOARD_USES_WRS_OMXIL_CORE := true
BOARD_USES_MRST_OMX := true
INTEL_VA := true

# Enabled to support ALAC
USE_FEATURE_ALAC := true
##############################################################
# Source: device/intel/mixins/groups/navigationbar/true/BoardConfig.mk
##############################################################
DEVICE_PACKAGE_OVERLAYS += device/intel/common/navigationbar/overlay

##############################################################
# Source: device/intel/mixins/groups/device-type/tablet/BoardConfig.mk
##############################################################
DEVICE_PACKAGE_OVERLAYS += device/intel/common/device-type/overlay-tablet
##############################################################
# Source: device/intel/mixins/groups/factory-scripts/true/BoardConfig.mk
##############################################################
# Include factory archive in 'make dist' output
TARGET_BUILD_INTEL_FACTORY_SCRIPTS := true

##############################################################
# Source: device/intel/mixins/groups/sepolicy/intel/BoardConfig.mk
##############################################################
# SELinux Policy
BOARD_SEPOLICY_DIRS := device/intel/common/sepolicy
BOARD_SEPOLICY_REPLACE := \
    domain.te

# please keep this list in alphabetical order
BOARD_SEPOLICY_UNION := \
    adbd.te \
    bluetooth.te \
    coreu.te \
    device.te \
    drmserver.te \
    efiprop.te \
    file_contexts \
    file.te \
    genfs_contexts \
    gpsd.te \
    hdcpd.te \
    init_shell.te \
    init.te \
    kernel.te \
    keymaster.te \
    keystore.te \
    mediaserver.te \
    netd.te \
    otp.te \
    platform_app.te \
    power_hal_helper.te \
    property_contexts \
    property.te \
    pstore-clean.te \
    recovery.te \
    service_contexts \
    service.te \
    setup_fs.te \
    shell.te \
    surfaceflinger.te \
    system_app.te \
    system_server.te \
    thermal.te \
    ueventd.te \
    untrusted_app.te \
    userfastboot.te \
    vold.te \
    wpa.te \
    asf.te \
    sensorhubd.te

# SELinux
ifneq (,$(filter $(TARGET_BUILD_VARIANT),eng userdebug))
BOARD_KERNEL_CMDLINE += enforcing=0 androidboot.selinux=permissive
endif

##############################################################
# Source: device/intel/mixins/groups/gps/bcm4752/BoardConfig.mk
##############################################################
GPS_CHIP_VENDOR := bcm
GPS_CHIP := 4752
##############################################################
# Source: device/intel/mixins/groups/serialport/ttyS0/BoardConfig.mk
##############################################################
BOARD_KERNEL_CMDLINE += console=ttyS0,115200n8
##############################################################
# Source: device/intel/mixins/groups/flashfiles/true/BoardConfig.mk
##############################################################
FLASHFILES_CONFIG ?= $(TARGET_DEVICE_DIR)/flashfiles.json
USE_INTEL_FLASHFILES := true

##############################################################
# Source: device/intel/mixins/groups/debug-logs/true/BoardConfig.mk
##############################################################
#enable aplogfs by default for eng and userdebug builds
ifneq ($(TARGET_BUILD_VARIANT),user)
ADDITIONAL_DEFAULT_PROPERTIES += persist.service.apklogfs.enable=1
endif
##############################################################
# Source: device/intel/mixins/groups/debug-crashlogd/true/BoardConfig.mk
##############################################################
# Enable crashlogd for eng and userdebug builds
ifneq ($(TARGET_BUILD_VARIANT),user)
CRASHLOGD_LOGS_PATH := "/data/logs"
CRASHLOGD_APLOG := true
CRASHLOGD_FULL_REPORT := true
endif
##############################################################
# Source: device/intel/mixins/groups/debug-coredump/true/BoardConfig.mk
##############################################################
# Enable core dump for eng and userdebug builds
ifneq ($(TARGET_BUILD_VARIANT),user)
ADDITIONAL_DEFAULT_PROPERTIES += persist.core.enabled=1
CRASHLOGD_COREDUMP := true
endif
##############################################################
# Source: device/intel/mixins/groups/bcu/true/BoardConfig.mk
##############################################################
BCUCPUFREQREL_CHT := true
##############################################################
# Source: device/intel/mixins/groups/silentlake/true/BoardConfig.mk
##############################################################
BOARD_SEPOLICY_UNION += \
    silentlake.te
##############################################################
# Source: device/intel/mixins/groups/libmds/mds/BoardConfig.mk
##############################################################
# Settings for the MDS and plug-ins:
TARGET_HAS_MULTIPLE_DISPLAY := true

PRODUCT_BOOT_JARS += com.intel.multidisplay
##############################################################
# Source: device/intel/mixins/groups/vpp/isv/BoardConfig.mk
##############################################################
# Settings for Intel Smart Video library:
TARGET_HAS_ISV := true

DEVICE_PACKAGE_OVERLAYS += device/intel/common/video_isv/overlay
##############################################################
# Source: device/intel/mixins/groups/libhealthd/intel/BoardConfig.mk
##############################################################
BOARD_HAL_STATIC_LIBRARIES += libhealthd.intel
##############################################################
# Source: device/intel/mixins/groups/sensor-hubs/ish/BoardConfig.mk
##############################################################
# enable ish libsensorhub
ENABLE_SENSOR_HUB_ISH := true

# enable ish sensor HAL
ENABLE_SENSOR_HAL_ISH := true

##############################################################
# Source: device/intel/mixins/groups/initrc-aosp/override/BoardConfig.mk
##############################################################
TARGET_PROVIDES_INIT_RC := true

##############################################################
# Source: device/intel/mixins/groups/wov/lpal/BoardConfig.mk
##############################################################
# LPAL(WoV)
INTEL_FEATURE_LPAL := true
##############################################################
# Source: device/intel/mixins/groups/asf/true/BoardConfig.mk
##############################################################
# Android Security Framework (IDPT-SE)
INTEL_FEATURE_ASF := true
# Supported ASF Version
PLATFORM_ASF_VERSION := 3
# Android Security Framework Licensed Permission
INTEL_FEATURE_PERM_LIC := true

PRODUCT_BOOT_JARS += com.intel.asf
##############################################################
# Source: device/intel/mixins/groups/pmic/dollar_cove_ti/BoardConfig.mk
##############################################################
USE_TI_FG_ALGO := true

##############################################################
# Source: device/intel/mixins/groups/art-config/default/BoardConfig.mk
##############################################################
# Enable dex-preoptimization to speed up the first boot sequence
# Note that this operation only works on Linux for now
WITH_DEXPREOPT := true

##############################################################
# Source: device/intel/mixins/groups/mixin-check/default/BoardConfig.mk
##############################################################
mixin_update := $(wildcard device/intel/mixins/mixin-update)

ifneq ($(mixin_update),)

# TARGET_DEVICE_DIR doesn't get expanded until later. so OK to reference
# this in BoardConfig.mk
.PHONY: check-mixins
check-mixins:
	device/intel/mixins/mixin-update --dry-run --spec $(TARGET_DEVICE_DIR)/mixins.spec

# This invocation of dumpvar gets called during the 'lunch' command. Hook it to
# do some additional checking.
dumpvar-TARGET_DEVICE: check-mixins
droidcore: check-mixins

endif

# ------------------ END MIX-IN DEFINITIONS ------------------
# Workaround BIOS looking for Microsoft string inside the bootloader
BOARD_FIRST_STAGE_LOADER := $(LOADER_PREBUILT)/kernelflinger/$(LOADER_TYPE)/kernelflinger.insecure.vendor.efi

# fuel gauge userspace helper
BOARD_SEPOLICY_DIRS += device/intel/cherrytrail/cht_cr_rvp/sepolicy
BOARD_SEPOLICY_UNION += fg_algo_iface.te
